# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: spacex/api/device/services/unlock/service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'spacex/api/device/services/unlock/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/spacex/api/device/services/unlock/service.proto\x12!SpaceX.API.Device.Services.Unlock\"\xbf\x02\n\x0fUnlockChallenge\x12 \n\tdevice_id\x18\x01 \x01(\tH\x00R\x08\x64\x65viceId\x88\x01\x01\x12\x19\n\x05nonce\x18\x02 \x01(\x0cH\x01R\x05nonce\x88\x01\x01\x12 \n\tsign_spki\x18\x04 \x01(\x0cH\x02R\x08signSpki\x88\x01\x01\x12(\n\rgrant_keydata\x18\x05 \x01(\tH\x03R\x0cgrantKeydata\x88\x01\x01\x12,\n\x0fservice_keydata\x18\x06 \x01(\tH\x04R\x0eserviceKeydata\x88\x01\x01\x12)\n\x10\x61uthority_grants\x18\x07 \x03(\tR\x0f\x61uthorityGrantsB\x0c\n\n_device_idB\x08\n\x06_nonceB\x0c\n\n_sign_spkiB\x10\n\x0e_grant_keydataB\x12\n\x10_service_keydata\"\x14\n\x12StartUnlockRequest\"\x9a\x01\n\x13StartUnlockResponse\x12 \n\tdevice_id\x18\x01 \x01(\tH\x00R\x08\x64\x65viceId\x88\x01\x01\x12\x19\n\x05nonce\x18\x02 \x01(\x0cH\x01R\x05nonce\x88\x01\x01\x12 \n\tsign_spki\x18\x03 \x01(\x0cH\x02R\x08signSpki\x88\x01\x01\x42\x0c\n\n_device_idB\x08\n\x06_nonceB\x0c\n\n_sign_spki\"w\n\x13\x46inishUnlockRequest\x12!\n\tchallenge\x18\x01 \x01(\x0cH\x00R\tchallenge\x88\x01\x01\x12!\n\tsignature\x18\x02 \x01(\x0cH\x01R\tsignature\x88\x01\x01\x42\x0c\n\n_challengeB\x0c\n\n_signature\">\n\x14\x46inishUnlockResponse\x12\x1b\n\x06status\x18\x01 \x01(\rH\x00R\x06status\x88\x01\x01\x42\t\n\x07_status2\x8e\x02\n\rUnlockService\x12|\n\x0bStartUnlock\x12\x35.SpaceX.API.Device.Services.Unlock.StartUnlockRequest\x1a\x36.SpaceX.API.Device.Services.Unlock.StartUnlockResponse\x12\x7f\n\x0c\x46inishUnlock\x12\x36.SpaceX.API.Device.Services.Unlock.FinishUnlockRequest\x1a\x37.SpaceX.API.Device.Services.Unlock.FinishUnlockResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spacex.api.device.services.unlock.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UNLOCKCHALLENGE']._serialized_start=87
  _globals['_UNLOCKCHALLENGE']._serialized_end=406
  _globals['_STARTUNLOCKREQUEST']._serialized_start=408
  _globals['_STARTUNLOCKREQUEST']._serialized_end=428
  _globals['_STARTUNLOCKRESPONSE']._serialized_start=431
  _globals['_STARTUNLOCKRESPONSE']._serialized_end=585
  _globals['_FINISHUNLOCKREQUEST']._serialized_start=587
  _globals['_FINISHUNLOCKREQUEST']._serialized_end=706
  _globals['_FINISHUNLOCKRESPONSE']._serialized_start=708
  _globals['_FINISHUNLOCKRESPONSE']._serialized_end=770
  _globals['_UNLOCKSERVICE']._serialized_start=773
  _globals['_UNLOCKSERVICE']._serialized_end=1043
# @@protoc_insertion_point(module_scope)
